# Generated by Django 5.2.16 on 2026-07-24 08:22

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("configuration", "0003_emaildistribution_messagegroup_parent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportChangeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_reference", models.CharField(db_index=True, max_length=100)),
                ("change_type", models.CharField(max_length=40)),
                ("object_type", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=100)),
                ("summary", models.CharField(max_length=500)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_change_records",
                        to="configuration.site",
                    ),
                ),
            ],
            options={
                "ordering": ("occurred_at", "pk"),
            },
        ),
        migrations.CreateModel(
            name="ReportingCohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("user_group", "User group"),
                            ("watch_group", "Watch group"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reporting_cohorts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reporting_cohorts",
                        to="configuration.site",
                    ),
                ),
            ],
            options={
                "ordering": ("name", "pk"),
            },
        ),
        migrations.CreateModel(
            name="ReportRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_code", models.CharField(db_index=True, max_length=8)),
                ("catalogue_version", models.PositiveSmallIntegerField(default=1)),
                ("criteria", models.JSONField(default=dict)),
                ("columns", models.JSONField(default=list)),
                ("rows", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("error", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-pk"),
                "indexes": [
                    models.Index(
                        fields=["actor", "status", "created_at"],
                        name="report_actor_status_time",
                    )
                ],
            },
        ),
    ]
