# Generated by Django 5.2.16 on 2026-07-23 23:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton",
                    models.BooleanField(default=True, editable=False, unique=True),
                ),
                (
                    "creation_anchor",
                    models.CharField(
                        choices=[
                            ("now", "Event time"),
                            ("release", "Release time"),
                            ("effective", "Effective time"),
                        ],
                        default="now",
                        max_length=12,
                    ),
                ),
                ("creation_offset_minutes", models.IntegerField(default=0)),
                (
                    "approval_anchor",
                    models.CharField(
                        choices=[
                            ("now", "Event time"),
                            ("release", "Release time"),
                            ("effective", "Effective time"),
                        ],
                        default="now",
                        max_length=12,
                    ),
                ),
                ("approval_offset_minutes", models.IntegerField(default=0)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                (
                    "timezone_name",
                    models.CharField(default="Europe/London", max_length=64),
                ),
                (
                    "maximum_attempts",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "retry_delay_minutes",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "archive_retention_days",
                    models.PositiveIntegerField(
                        default=365,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.SlugField(max_length=80)),
                ("payload", models.JSONField(default=dict)),
                ("deduplication_key", models.CharField(max_length=180, unique=True)),
                ("available_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("published", "Published"),
                            ("dead", "Dead letter"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("available_at", "pk"),
                "indexes": [models.Index(fields=["status", "available_at"], name="outbox_due")],
            },
        ),
        migrations.CreateModel(
            name="LifecycleJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                (
                    "transition",
                    models.CharField(
                        choices=[
                            ("release", "Release"),
                            ("effective", "Become effective"),
                            ("expire", "Expire"),
                            ("archive", "Archive"),
                            ("retention_review", "Retention review"),
                            ("unapproved_alert", "Unapproved-at-effective alert"),
                        ],
                        max_length=24,
                    ),
                ),
                ("due_at", models.DateTimeField()),
                ("deduplication_key", models.CharField(max_length=180, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                            ("dead", "Dead letter"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lifecycle_jobs",
                        to="messaging.message",
                    ),
                ),
            ],
            options={
                "ordering": ("due_at", "pk"),
                "indexes": [models.Index(fields=["status", "due_at"], name="lifecycle_due")],
            },
        ),
        migrations.CreateModel(
            name="NotificationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("created", "Message created"),
                            ("approved", "Message approved"),
                            ("unapproved_effective", "Unapproved at effective time"),
                            ("manual_resend", "Manual resend"),
                        ],
                        max_length=24,
                    ),
                ),
                ("recipients", models.JSONField(default=list)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("deduplication_key", models.CharField(max_length=180, unique=True)),
                ("scheduled_at", models.DateTimeField()),
                ("next_attempt_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("dead", "Dead letter"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notification_jobs",
                        to="messaging.message",
                    ),
                ),
            ],
            options={
                "ordering": ("next_attempt_at", "pk"),
                "indexes": [
                    models.Index(fields=["status", "next_attempt_at"], name="notification_due")
                ],
            },
        ),
    ]
