# Generated by Django 5.2.16 on 2026-07-23 22:54

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("configuration", "0003_emaildistribution_messagegroup_parent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessagePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton",
                    models.BooleanField(default=True, editable=False, unique=True),
                ),
                ("enforce_pdf_filename_match", models.BooleanField(default=False)),
                ("maximum_pdf_bytes", models.PositiveIntegerField(default=10485760)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message_id", models.SlugField(max_length=80, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("botd", "Brief of the Day"),
                            ("instruction", "Instruction"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft / Unapproved"),
                            ("approved_pending_release", "Approved pending release"),
                            (
                                "released_pending_effective",
                                "Released pending effective",
                            ),
                            ("effective", "Effective"),
                            ("expired", "Expired"),
                            ("archived", "Archived"),
                            ("withdrawn", "Withdrawn"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=32,
                    ),
                ),
                ("lock_version", models.PositiveIntegerField(default=1)),
                ("current_version_number", models.PositiveIntegerField(default=1)),
                ("archive_on_expiry", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approvers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="messages_to_approve",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="configuration.messagetype",
                    ),
                ),
                (
                    "originator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="originated_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subtype",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="messages",
                        to="configuration.messagesubtype",
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="messaging.message",
                    ),
                ),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="LifecycleCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idempotency_key", models.UUIDField()),
                ("command", models.SlugField(max_length=40)),
                (
                    "resulting_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft / Unapproved"),
                            ("approved_pending_release", "Approved pending release"),
                            (
                                "released_pending_effective",
                                "Released pending effective",
                            ),
                            ("effective", "Effective"),
                            ("expired", "Expired"),
                            ("archived", "Archived"),
                            ("withdrawn", "Withdrawn"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=32,
                    ),
                ),
                ("aggregate_version", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="messaging.message",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageAudienceRight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "right",
                    models.CharField(
                        choices=[
                            ("prohibited", "Prohibited"),
                            ("allowed", "Allowed"),
                            ("mandatory", "Mandatory"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audience_rights",
                        to="messaging.message",
                    ),
                ),
                (
                    "message_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="message_rights",
                        to="configuration.messagegroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("draft", "Draft / Unapproved"),
                            ("approved_pending_release", "Approved pending release"),
                            (
                                "released_pending_effective",
                                "Released pending effective",
                            ),
                            ("effective", "Effective"),
                            ("expired", "Expired"),
                            ("archived", "Archived"),
                            ("withdrawn", "Withdrawn"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft / Unapproved"),
                            ("approved_pending_release", "Approved pending release"),
                            (
                                "released_pending_effective",
                                "Released pending effective",
                            ),
                            ("effective", "Effective"),
                            ("expired", "Expired"),
                            ("archived", "Archived"),
                            ("withdrawn", "Withdrawn"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("aggregate_version", models.PositiveIntegerField()),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="message_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="messaging.message",
                    ),
                ),
            ],
            options={
                "ordering": ("occurred_at", "pk"),
            },
        ),
        migrations.CreateModel(
            name="MessageVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=240)),
                ("summary", models.TextField(blank=True)),
                ("text_content", models.TextField(blank=True)),
                ("release_at", models.DateTimeField()),
                ("effective_at", models.DateTimeField(blank=True, null=True)),
                ("expiry_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="message_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="messaging.message",
                    ),
                ),
            ],
            options={
                "ordering": ("message", "version_number"),
            },
        ),
        migrations.CreateModel(
            name="FileAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("display", "Display PDF"), ("print", "Print PDF")],
                        max_length=12,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "storage_key",
                    models.CharField(editable=False, max_length=255, unique=True),
                ),
                ("content_type", models.CharField(max_length=100)),
                ("byte_size", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("quarantined", "Quarantined"),
                            ("clean", "Clean"),
                            ("infected", "Infected"),
                            ("error", "Scan error"),
                        ],
                        default="quarantined",
                        max_length=16,
                    ),
                ),
                ("scan_detail", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_message_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="files",
                        to="messaging.messageversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("justification", models.TextField()),
                ("validity_justification", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="message_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approvals",
                        to="messaging.message",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approvals",
                        to="messaging.messageversion",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["message_id"], name="message_id_lookup"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["status", "updated_at"], name="message_status_updated"),
        ),
        migrations.AddConstraint(
            model_name="lifecyclecommand",
            constraint=models.UniqueConstraint(
                fields=("message", "idempotency_key"), name="unique_message_command_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="messageaudienceright",
            constraint=models.UniqueConstraint(
                fields=("message", "message_group"), name="unique_message_group_right"
            ),
        ),
        migrations.AddConstraint(
            model_name="messageversion",
            constraint=models.UniqueConstraint(
                fields=("message", "version_number"), name="unique_message_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="messageversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("expiry_at__gt", models.F("release_at"))),
                name="message_expiry_after_release",
            ),
        ),
        migrations.AddConstraint(
            model_name="messageversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_at__isnull", True),
                    ("expiry_at__gte", models.F("effective_at")),
                    _connector="OR",
                ),
                name="message_expiry_not_before_effective",
            ),
        ),
        migrations.AddConstraint(
            model_name="messageversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("effective_at__isnull", True),
                    ("effective_at__gte", models.F("release_at")),
                    _connector="OR",
                ),
                name="message_effective_not_before_release",
            ),
        ),
        migrations.AddConstraint(
            model_name="fileasset",
            constraint=models.UniqueConstraint(
                fields=("version", "role"), name="one_file_per_version_role"
            ),
        ),
    ]
