# Generated by Django 5.2.16 on 2026-07-24 07:12

from django.conf import settings
from django.db import migrations, models


def copy_text_content(apps, schema_editor):
    message_version = apps.get_model("messaging", "MessageVersion")
    message_version.objects.exclude(text_content="").update(
        searchable_content=models.F("text_content")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="messageversion",
            name="searchable_content",
            field=models.TextField(
                blank=True,
                help_text="Text extracted from the protected display content for scoped search.",
            ),
        ),
        migrations.RunPython(copy_text_content, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="messageversion",
            name="title",
            field=models.CharField(db_index=True, max_length=240),
        ),
        migrations.AddIndex(
            model_name="messageversion",
            index=models.Index(fields=["release_at", "message"], name="version_release_message"),
        ),
        migrations.AddIndex(
            model_name="messageversion",
            index=models.Index(
                fields=["effective_at", "message"], name="version_effective_message"
            ),
        ),
        migrations.AddIndex(
            model_name="messageversion",
            index=models.Index(fields=["expiry_at", "message"], name="version_expiry_message"),
        ),
    ]
