# Generated by Django 5.2.16 on 2026-07-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0002_messageversion_searchable_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="purged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
