# Generated by Django 5.2.16 on 2026-07-23 22:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("configuration", "0002_alter_messagegroup_id_alter_messagetype_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                ("email_address", models.EmailField(max_length=254)),
                ("use_as_email", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="messagegroup",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="configuration.messagegroup",
            ),
        ),
        migrations.AddField(
            model_name="messagetype",
            name="default_content_type",
            field=models.CharField(
                choices=[("text", "Text"), ("pdf", "PDF")], default="text", max_length=8
            ),
        ),
        migrations.AddField(
            model_name="messagetype",
            name="display_at_logon",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="messagetype",
            name="has_effective_date",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="messagetype",
            name="has_subtypes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="messagetype",
            name="menu_view",
            field=models.CharField(
                choices=[
                    ("mandatory", "Mandatory"),
                    ("other", "Other"),
                    ("both", "Both"),
                ],
                default="both",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="messagetype",
            name="requires_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="messagetype",
            name="searchable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="messagetype",
            name="view_mode",
            field=models.CharField(
                choices=[("full", "Full page"), ("panel", "Side panel")],
                default="full",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="MessageGroupType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                ("exclusive_membership", models.BooleanField(default=False)),
                (
                    "allowed_message_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to allow all message types.",
                        related_name="group_types",
                        to="configuration.messagetype",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="configuration.messagegrouptype",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="messagegroup",
            name="group_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="message_groups",
                to="configuration.messagegrouptype",
            ),
        ),
        migrations.CreateModel(
            name="MessageSubType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "minimum_validity_days",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "maximum_validity_days",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "email_distributions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="subtypes",
                        to="configuration.emaildistribution",
                    ),
                ),
                (
                    "message_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subtypes",
                        to="configuration.messagetype",
                    ),
                ),
                (
                    "primary_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="message_subtypes",
                        to="configuration.primarymessagegroup",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                ("identification", models.CharField(max_length=100)),
                (
                    "primary_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sectors",
                        to="configuration.primarymessagegroup",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="messagegroup",
            name="sectors",
            field=models.ManyToManyField(
                blank=True, related_name="message_groups", to="configuration.sector"
            ),
        ),
        migrations.AddConstraint(
            model_name="messagegroup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("parent__isnull", True),
                    models.Q(("parent", models.F("id")), _negated=True),
                    _connector="OR",
                ),
                name="message_group_not_own_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="messagegrouptype",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("parent__isnull", True),
                    models.Q(("parent", models.F("id")), _negated=True),
                    _connector="OR",
                ),
                name="group_type_not_own_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="messagesubtype",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("maximum_validity_days__gte", models.F("minimum_validity_days"))
                ),
                name="subtype_validity_min_lte_max",
            ),
        ),
        migrations.AddConstraint(
            model_name="messagesubtype",
            constraint=models.UniqueConstraint(
                fields=("primary_group", "message_type", "name"),
                name="unique_subtype_name_per_pmg_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="sector",
            constraint=models.UniqueConstraint(
                fields=("primary_group", "identification"),
                name="unique_sector_identification_per_pmg",
            ),
        ),
    ]
