# Generated by Django 5.2.16 on 2026-07-24 08:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("content_sha256", models.CharField(max_length=64)),
                ("staged_content", models.TextField()),
                ("schema_version", models.CharField(default="1", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("staged", "Ready for review"),
                            ("rejected", "File in error"),
                            ("committed", "Process complete"),
                        ],
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("staged_at", models.DateTimeField(auto_now_add=True)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "staged_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staged_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-staged_at",),
            },
        ),
        migrations.CreateModel(
            name="ImportChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("site_code", models.SlugField(max_length=64)),
                ("action", models.CharField(max_length=16)),
                ("user_id", models.CharField(max_length=150)),
                ("payload", models.JSONField(default=dict)),
                ("selected", models.BooleanField(default=True)),
                ("applied", models.BooleanField(default=False)),
                ("outcome", models.CharField(blank=True, max_length=500)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes",
                        to="sapimport.importbatch",
                    ),
                ),
            ],
            options={
                "ordering": ("site_code", "row_number"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "row_number"), name="unique_import_batch_row"
                    )
                ],
            },
        ),
    ]
