# Generated by Django 5.2.16 on 2026-07-23 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assurance", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
